services:
    nginx:
        container_name: nginx-proxy
        hostname: nginx-proxy
        restart: unless-stopped
        image: nginx:alpine
        network_mode: host
        volumes:
            - ./nginx:/etc/nginx:ro
            - ./nginx/ssl:/etc/nginx/ssl:ro
            - nginx_logs:/var/log/nginx
        depends_on: []
        healthcheck:
            test: ["CMD", "nginx", "-t"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 30s

volumes:
    nginx_logs: